package com.example.familymenu.family.repository;
import com.example.familymenu.family.domain.*; import org.springframework.context.annotation.Profile; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.jdbc.support.*; import org.springframework.stereotype.Repository; import java.sql.*; import java.util.*;
@Repository @Profile("!memory") public class JdbcFamilyRepository implements FamilyRepository {
 private final JdbcTemplate jdbc; public JdbcFamilyRepository(JdbcTemplate j){jdbc=j;}
 @org.springframework.transaction.annotation.Transactional public Family createForUser(String name,Long userId){KeyHolder k=new GeneratedKeyHolder();jdbc.update(c->{PreparedStatement s=c.prepareStatement("INSERT INTO families(name,owner_user_id) VALUES(?,?)",Statement.RETURN_GENERATED_KEYS);s.setString(1,name);s.setLong(2,userId);return s;},k);Long fid=k.getKey().longValue();jdbc.update("INSERT INTO family_members(family_id,user_id,role) VALUES(?,?, 'OWNER')",fid,userId);return new Family(fid,name,userId);}
 public Optional<Family> findById(Long id){List<Family> x=jdbc.query("SELECT id,name,owner_user_id FROM families WHERE id=?",new Object[]{id},(r,n)->new Family(r.getLong(1),r.getString(2),r.getLong(3)));return x.isEmpty()?Optional.<Family>empty():Optional.of(x.get(0));}
 public List<Family> findByUserNickname(String nickname){return jdbc.query("SELECT DISTINCT f.id,f.name,f.owner_user_id FROM families f JOIN family_members fm ON fm.family_id=f.id JOIN users u ON u.id=fm.user_id WHERE u.nickname=? ORDER BY f.id",new Object[]{nickname},(r,n)->new Family(r.getLong(1),r.getString(2),r.getLong(3)));}
 public List<Family> findByUserId(Long userId){return jdbc.query("SELECT DISTINCT f.id,f.name,f.owner_user_id FROM families f JOIN family_members fm ON fm.family_id=f.id WHERE fm.user_id=? ORDER BY f.id",new Object[]{userId},(r,n)->new Family(r.getLong(1),r.getString(2),r.getLong(3)));}
 public List<FamilyMember> findMembers(Long id){return jdbc.query("SELECT fm.id,fm.family_id,fm.user_id,u.nickname,fm.role,u.avatar_url FROM family_members fm JOIN users u ON u.id=fm.user_id WHERE fm.family_id=? ORDER BY fm.id",new Object[]{id},(r,n)->new FamilyMember(r.getLong(1),r.getLong(2),r.getLong(3),r.getString(4),r.getString(5),r.getString(6)));}
 public boolean isMember(Long familyId,Long userId){Integer count=jdbc.queryForObject("SELECT COUNT(1) FROM family_members WHERE family_id=? AND user_id=?",Integer.class,familyId,userId);return count!=null&&count>0;}
 public FamilyMember addMemberUserId(Long fid,Long userId,String nickname,String role){jdbc.update("INSERT INTO family_members(family_id,user_id,role) VALUES(?,?,?)",fid,userId,role);return findMembers(fid).stream().filter(m->m.getUserId().equals(userId)).findFirst().get();}
 public FamilyMember addMember(Long fid,String nick,String role){List<Long> ids=jdbc.query("SELECT id FROM users WHERE nickname=? ORDER BY id LIMIT 1",new Object[]{nick},(r,n)->r.getLong(1)); Long uid;if(ids.isEmpty()){jdbc.update("INSERT INTO users(nickname) VALUES(?)",nick);uid=jdbc.queryForObject("SELECT LAST_INSERT_ID()",Long.class);} else {uid=ids.get(0);} return addMemberUserId(fid,uid,nick,role);}
 public boolean updateMemberRole(Long fid,Long mid,String role){return jdbc.update("UPDATE family_members SET role=? WHERE id=? AND family_id=? AND role <> 'OWNER'",role,mid,fid)>0;}
 public boolean removeMember(Long fid,Long mid){return jdbc.update("DELETE FROM family_members WHERE id=? AND family_id=? AND role <> 'OWNER'",mid,fid)>0;}
 public boolean deleteFamily(Long fid){return jdbc.update("DELETE FROM families WHERE id=?",fid)>0;}
}
