package com.example.familymenu.family.repository;
import com.example.familymenu.family.domain.*; import org.springframework.context.annotation.Profile; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.jdbc.support.*; import org.springframework.stereotype.Repository; import java.sql.*; import java.util.*;
@Repository @Profile("!memory") public class JdbcFamilyRepository implements FamilyRepository {
 private final JdbcTemplate jdbc; public JdbcFamilyRepository(JdbcTemplate j){jdbc=j;}
 public Family create(String name,String ownerName){jdbc.update("INSERT INTO users(nickname) VALUES(?)",ownerName); Long uid=jdbc.queryForObject("SELECT LAST_INSERT_ID()",Long.class); KeyHolder k=new GeneratedKeyHolder(); jdbc.update(c->{PreparedStatement s=c.prepareStatement("INSERT INTO families(name,owner_user_id) VALUES(?,?)",Statement.RETURN_GENERATED_KEYS);s.setString(1,name);s.setLong(2,uid);return s;},k); Long fid=k.getKey().longValue(); jdbc.update("INSERT INTO family_members(family_id,user_id,role) VALUES(?,?, 'OWNER')",fid,uid); return new Family(fid,name,uid);}
 public Optional<Family> findById(Long id){List<Family> x=jdbc.query("SELECT id,name,owner_user_id FROM families WHERE id=?",new Object[]{id},(r,n)->new Family(r.getLong(1),r.getString(2),r.getLong(3)));return x.isEmpty()?Optional.<Family>empty():Optional.of(x.get(0));}
 public List<FamilyMember> findMembers(Long id){return jdbc.query("SELECT fm.id,fm.family_id,fm.user_id,u.nickname,fm.role FROM family_members fm JOIN users u ON u.id=fm.user_id WHERE fm.family_id=? ORDER BY fm.id",new Object[]{id},(r,n)->new FamilyMember(r.getLong(1),r.getLong(2),r.getLong(3),r.getString(4),r.getString(5)));}
 public FamilyMember addMember(Long fid,String nick,String role){List<Long> ids=jdbc.query("SELECT id FROM users WHERE nickname=? ORDER BY id LIMIT 1",new Object[]{nick},(r,n)->r.getLong(1)); Long uid; if(ids.isEmpty()){jdbc.update("INSERT INTO users(nickname) VALUES(?)",nick);uid=jdbc.queryForObject("SELECT LAST_INSERT_ID()",Long.class);} else {uid=ids.get(0);} final Long userId=uid; jdbc.update("INSERT INTO family_members(family_id,user_id,role) VALUES(?,?,?)",fid,userId,role); return findMembers(fid).stream().filter(m->m.getUserId().equals(userId)).findFirst().get();}
 public boolean removeMember(Long fid,Long mid){return jdbc.update("DELETE FROM family_members WHERE id=? AND family_id=? AND role <> 'OWNER'",mid,fid)>0;}
}
