spring:
  application:
    name: family-menu-backend
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://127.0.0.1:3306/family_menu?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:bendan521}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always

server:
  port: 8081

wechat:
  appid: ${WECHAT_APPID:wxbc338b2070fea762}
  secret: ${WECHAT_SECRET:}
